FROM node:lts-alpine as builder

# Установка необходимых зависимостей
RUN apk add --no-cache \
    udev \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    tzdata

# Установка временной зоны (замените на вашу)
ENV TZ=Europe/Moscow

ENV PUPPETEER_CACHE_DIR=/root/.cache/puppeteer

WORKDIR /app

COPY package*.json /

COPY . .

RUN npm install && npx puppeteer browsers install chrome

RUN mkdir -p var/log

RUN mkdir -p session/odin

EXPOSE 5000

CMD ["npm", "run", "start:build"]

