version: '3.9'
services:
    learn_bot:
        container_name: learn_bot
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile_local
        expose:
            - '5000'
        ports:
            - '127.0.0.1:5000:5000'
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=${NODE_ENV} #production development
            - PORT=${PORT}
            - ODIN_EMAIL=${ODIN_EMAIL}
            - ODIN_PASSWORD=${ODIN_PASSWORD}
networks:
    learn_bot_network:
        driver: bridge
