name: Deploy to VM

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install expect
              run: sudo apt-get install -y expect

            - name: Add private key with passphrase to ssh-agent
              run: |
                  expect << EOF
                  spawn ssh-add /dev/fd/0
                  expect "Enter passphrase for /dev/fd/0:"
                  send "$SSH_KEY_PASSPHRASE\r"
                  expect eof
                  EOF
              env:
                  SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}

            - name: Copy files to VM
              run: |
                  scp -r -o StrictHostKeyChecking=no . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/path/to/deploy

            - name: Execute deployment commands on VM
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
                    cd ~/Zoom-bot
                    docker compose down
                    docker compose up -d --build
                  EOF
